a.out: project_main.o Manager.o Customer.o Bank.o mystring.o uart.o
	gcc project_main.o Manager.o Customer.o Bank.o mystring.o uart.o
project_main.o: project_main.c
	gcc -c project_main.c
Manager.o: Manager.c
	gcc -c Manager.c
Customer.o: Customer.c
	gcc -c Customer.c
Bank.o: Bank.c
	gcc -c Bank.c
mystring.o: mystring.c
	gcc -c mystring.c
uart.o: uart.c
	gcc -c uart.c
